Throwing exception in a finally block is confusing. It may mask exception or a defect of the code, it also render code cleanup uninstable. Example :
<pre>
public class Foo
{
  public void bar()
  {
    try {
    // Here do some stuff
    }
    catch( Exception e) {
    // Handling the issue
    }
    finally
    {
      // is this really a good idea ?
      throw new Exception();
    }
  }
}
</pre>

<p>
  This rule is deprecated, use {rule:squid:S1163} instead.
</p>
